services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: redis_cache

  server:
  build: .
  container_name: lmgate-server

  volumes:
    - ./input:/data/input   # ğŸ‘ˆ (1) Ù‡Ù†Ø§ Ø§Ù„Ø¥Ø¶Ø§ÙØ©

  environment:
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    - REDIS_ADDR=redis:6379
    - AUTO_PROCESS=true     # ğŸ‘ˆ (2) ÙˆÙ‡Ù†Ø§

  depends_on:
    - rabbitmq
    - redis
