services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"

  redis:
    image: redis:alpine
    container_name: redis_cache

  server:
    build: .
    container_name: lmgate-server
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_ADDR=redis:6379
    depends_on:
      - rabbitmq
      - redis